image: node:latest

stages:
    - Code Quality

# cache:
#     key: NODE_DEPENDENCIES
#     paths:
#     - node_modules/

before_script:
    - npm run bootstrap

lint-js:
    stage: Code Quality
    script:
        - npm run lint
